# 開発環境用

version: '3.7'

services:
  app:
    build: ./app # Dockerfileがあるディレクトリ
    container_name: node16
    tty: true # コンテナの起動を継続させる
    ports:
      - '80:3000'
    restart: always
    volumes:
      - ./app/express:/usr/src/express
    depends_on:
      - db

  db:
    build: ./db
    container_name: mysql8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD

volumes:
  db_data: # volumeが存在しないときtouhan-backend_db_dataという名前のvolumeが作成される
